services:
  datadog:
    container_name: datadog
    image: "gcr.io/datadoghq/agent:latest"
    ports:
      - "8126:8126"
    environment:
      - DD_API_KEY=
      - DD_SITE=datadoghq.com  # Default. Change to eu.datadoghq.com, us3.datadoghq.com, us5.datadoghq.com as appropriate for your org
      - DD_APM_ENABLED=true    # Enable APM
      - DD_TRACE_FLASK_ENABLED=false
      - DD_TRACE_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_INJECTION=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      
  scorms:
    #image:
    container_name: scorms
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.oss
    ports:
      - "80:80"
    environment:
      - DD_SERVICE=scorms2
      - DD_ENV=stage
      - DD_AGENT_HOST=datadog
      - DD_LOGS_INJECTION=true
      - S3_BUCKET_NAME=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - S3_SERVER=s3.us-east-1.amazonaws.com
      - S3_SERVER_PORT=443
      - S3_SERVER_PROTO=https
      - S3_REGION=us-east-1
      - S3_STYLE=virtual
      - DEBUG=true
      - AWS_SIGS_VERSION=4
      - ALLOW_DIRECTORY_LIST=true
      - PROVIDE_INDEX_PAGE=true
      - APPEND_SLASH_FOR_POSSIBLE_DIRECTORY=false
      - PROXY_CACHE_MAX_SIZE=10g
      - PROXY_CACHE_INACTIVE=60m
      - PROXY_CACHE_VALID_OK=1h
      - PROXY_CACHE_VALID_NOTFOUND=1m
      - PROXY_CACHE_VALID_FORBIDDEN=30s
      - STRIP_LEADING_DIRECTORY_PATH=/somepath
